ndcn/omicser

README.Rmd, README.md
=> Overview image for README

R/setup_helpers.R
Error in roxygen2 @inport tags for setup_helpers fix:  read.config -> write.config.
=> fix setup_helpers.R roxygen2 @import -> write.config

R/mod_additional_info.R, inst/app/www/additional_info.Rmd
Prevents failure if additional_info.Rmd has not be curated.  Still need to update documentation / instructions to as for this curation.
=> fix  render to failsafe

vignettes/04_configuration.Rmd, vignettes/06_sharing.Rmd
.Rmds updated.  site still needs to e rendered.
=> expanded 04_configuration and 06_sharing vignettes

.gitignore, R/app_server.R, R/mod_pg_vis_comp.R, vignettes/examples/curate_yassene_lipids.R
Found a couple small errors during environment troubleshooting.  (hence branch name). 
The change to data.table from dplyr in subsetting data for volcano plotting created an error in the coloring which is now fixed.
=> Troubleshoot

DESCRIPTION, R/app_server.R, R/pre_process_helpers.R, dev/02_dev.R, renv.lock
This should fix a variety of bioconductor incompatibilities...
=> depricate sceasy and bioconductor requiriements

R/fct_pg_diff_expr.R, R/mod_pg_diff_expr.R
bat commit squished these... un-deleting
=> replace missing *diff_exp.R

R/fct_ingestor.R, R/fct_pg_expression.R, app_config.yml, dev/run_dev2.R
=> fix color bug in fct_pg_expression

R/setup_helpers.R
depricate golem dev testing/handling
=> fix get_config bug

README.md
quick update... need to get the github actions to automatically do this...
=> render README.md with updated README.Rmd

.Rbuildignore, Dockerfile, docker_stuff/.Renviron, docker_stuff/app_config.yml, docker_stuff/install_py_env.R, vignettes/docker.Rmd
I added everything so that anyone can make his own docker container with omicser running in it. A vignette is added with some explanation.
=> Added everything to create a docker container.

README.Rmd, vignettes/00_quickstart.Rmd, vignettes/02_data_curation.Rmd
why is the pkgdown action failing??
=> update readme... testing actions

R/mod_pg_table.R, R/mod_table.R, examples/README.md, examples/dev_run_browser_script.R, examples/install_script.R, examples/pbmc3k_curate_and_config.R, examples/run_browser_script.R, vignettes/01_installation.Rmd, vignettes/02_data_curation.Rmd, vignettes/03_configuration.Rmd
small fix to data-table rendering... (possible DT update related)
+
rationalized example scripts
=> fix datatable (DT) rendering bug & update example scripts

vignettes/03_configuration.Rmd
=> fixing 03_configuration.Rmd

R/mod_ingestor.R, examples/assert_python_script.R, examples/dev_run_browser_script.R, examples/install_script.R, examples/pbmc3k_curate_and_config.R, examples/proteomics_curate_and_config.R, examples/run_browser_script.R, vignettes/04_launching.Rmd, vignettes/browsing.Rmd
=> small example fixes

R/fct_ingestor.R, R/mod_ingestor.R
This should fix issue #156. The meta data of the database is now showing correctly.
=> Database meta data now showing correctly.

R/mod_omic_selector.R
This should avoid some overlap of components in the side selector (see issue #159 ).
=> Adjusted the position of some components to avoid overlap.

R/mod_pg_diff_expr.R
Check if there is data loaded to create the boxplot from a click in the volcano plot. This should fix issue #162.
=> fix issue 162

R/mod_pg_diff_expr.R
Option added to select raw or adjuste p-values for the volcano plot (see issue #158). The default is set to the raw p-values. Now the hover also shows the correct p-values.
=> Option added to select raw or adjuste p-values for the volcano plot.

R/mod_ingestor.R, R/mod_side_selector.R
Found some small typo's and before I forget about them I just send it like this.
=> Corrected some typo's.

R/mod_pg_table.R
Ok 3rd attempt, I missed that the main-dev repo was there. This should get rid of list-cols warnings when using the app.
=> Get rid of list-cols warnings.

R/fct_curation_lipid.R, R/mod_curation_lipid.R
Added a check to see if a database folder name already exists.
=> Check if a database folder exists in the database root.
